'use client';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { AnnotatedImage } from '@/components/AnnotatedImage';
import { VerdictCard } from '@/components/VerdictCard';
import { getReportUrl, getScan } from '@/lib/api';
import type { ScanResponse } from '@/lib/types';
interface ScanResult { imageDataUrl: string; imageWidth: number; imageHeight: number; verdicts: ScanResponse['verdicts']; }
export default function ScanResultPage() { const params = useParams<{ id: string }>(); const scanId = Number.parseInt(params.id, 10); const [scan, setScan] = useState<ScanResult | null>(null); const [error, setError] = useState<string | null>(null); useEffect(() => { const cached = sessionStorage.getItem(`scan:${scanId}`); if (cached) { try { setScan(JSON.parse(cached)); return; } catch {} } getScan(scanId).then((data) => setScan({ imageDataUrl: `data:image/png;base64,${data.scan.image_b64}`, imageWidth: data.scan.image_meta.width, imageHeight: data.scan.image_meta.height, verdicts: data.verdicts })).catch((reason) => setError(reason instanceof Error ? reason.message : 'unknown')); }, [scanId]); if (error) return <div className="p-6 text-red-700">Error: {error}</div>; if (!scan) return <div className="p-6">Loading…</div>; const overall = scan.verdicts.some((v) => v.status === 'fail') ? 'fail' : scan.verdicts.some((v) => v.status === 'warn') ? 'warn' : 'pass'; return <main className="mx-auto max-w-6xl space-y-6 p-6"><div className="flex items-center justify-between"><h1 className="text-2xl font-bold">Scan #{scanId}</h1><div className="flex gap-3"><a href="/" className="rounded border px-4 py-2 text-sm">New scan</a><a href={getReportUrl(scanId)} target="_blank" rel="noopener noreferrer" className="rounded bg-blue-600 px-4 py-2 text-sm text-white">Download PDF</a></div></div><div className="text-lg">Overall status: <span className={`font-semibold ${overall === 'pass' ? 'text-pass' : overall === 'fail' ? 'text-fail' : 'text-warn'}`}>{overall.toUpperCase()}</span></div><div className="grid gap-6 md:grid-cols-2"><div className="rounded border bg-white p-3"><AnnotatedImage imageSrc={scan.imageDataUrl} verdicts={scan.verdicts} /></div><div className="space-y-3">{scan.verdicts.map((verdict) => <VerdictCard key={verdict.rule_id} verdict={verdict} />)}</div></div></main>; }
